spring.application.name=blog

# URL de conexão: altera o "nome_do_seu_banco" para o banco que você criou no seu MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/blog_api

# Seu usuário do MySQL
spring.datasource.username=root

# A senha que você colocou quando instalou o MySQL
spring.datasource.password=root

# Mostra no console os comandos SQL que o Spring gerar (bom pra você entender o que tá rolando)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true